import type { Metadata } from 'next'
import { Oswald } from 'next/font/google'
import { AuthProvider } from './providers'
import './globals.css'
import Navbar from '../../components/navbar/navbar'
import 'bootstrap/dist/css/bootstrap.min.css';


const oswald = Oswald({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <AuthProvider>
          <Navbar/>
          {children}</AuthProvider>
        </body>
    </html>
  )
}
